<a href="https://colab.research.google.com/github/AyrtonFrederikFERNANDEZ/FRK/blob/main/lab3y4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#EJERCICIO 1
# IMPRIME LOS NUMEROS PARES DE 1 A 100
def imprimir_pares_recursivo(numero):
    if numero <= 100:
        if numero % 2 == 0:  #está verificando si el número es divisible por 2, es decir, si es un número par
            print(numero)
        imprimir_pares_recursivo(numero + 1) #es una llamada recursiva a la misma función

# Llamada inicial a la función
imprimir_pares_recursivo(1)


2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [1]:
#ejercicios 2
def suma_hasta_n(n):
    if n == 1:
        return 1
    else:
        return n + suma_hasta_n(n - 1)

def imprimir_suma_hasta_n(n):
    suma = suma_hasta_n(n)
    return (f"La suma de los números del 1 al {n} es: {suma}")

# Ejemplo de uso
imprimir_suma_hasta_n(10)

'La suma de los números del 1 al 10 es: 55'

In [ ]:
#ejercicio 3
#
def imprimir_piramide_recursiva(n, fila=1):
    if fila > n:
        return

    imprimir_linea(fila, 1)
    imprimir_piramide_recursiva(n, fila + 1)

def imprimir_linea(fila, columna):
    if columna > fila:
        print()  # Salto de línea al final de la fila
        return

    print(columna, end=" ")
    imprimir_linea(fila, columna + 1)

# Solicitar al usuario que ingrese el valor de n
n = int(input("Ingrese el valor de n para la pirámide: "))

# Llamada inicial a la función
imprimir_piramide_recursiva(n)


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 10 


In [2]:
### Ejercicio 04
def imprimir_piramide_invertida(n, i=1):
    if n == 0:
        return  # Caso base para evitar la recursión infinita

    if i <= n:
        # Imprime espacios en blanco para alinear los números
        print(" " * (n - i), end="")

        # Imprime los números en orden descendente
        for j in range(i, 0, -1):
            print(j, end=" ")

        print()  # Salto de línea

        # Llama recursivamente a la función con el siguiente nivel de la pirámide
        imprimir_piramide_invertida(n, i + 1)

# Ejemplo de uso
imprimir_piramide_invertida(5)

    1 
   2 1 
  3 2 1 
 4 3 2 1 
5 4 3 2 1 


In [ ]:
#ejercicio 5
#tabla de multiplicar
def imprimir_tabla_multiplicar(n, multiplicador=1):
    if multiplicador > 10:
        return

    resultado = n * multiplicador
    print(f"{n} x {multiplicador} = {resultado}")

    imprimir_tabla_multiplicar(n, multiplicador + 1)

# Solicitar al usuario que ingrese el valor de n
n = int(input("Ingrese el valor de n para la tabla de multiplicar: "))

# Llamada inicial a la función
imprimir_tabla_multiplicar(n)


Ingrese el valor de n para la tabla de multiplicar: 11
11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110


In [3]:
#  Ejercicio 06
import numpy as np
# Creacion de la matriz con np.array
matriz = np.array([[2,3,2.5],[44,4,6],[14,23,1]])
print(matriz)


[[ 2.   3.   2.5]
 [44.   4.   6. ]
 [14.  23.   1. ]]


In [ ]:
#ejercicio 7
#	Crea una matriz de números complejos
import numpy as np

# Definir una matriz de números complejos
matriz_compleja = np.array([[1 + 2j, 2 - 1j], [3j, 4]])

# Mostrar la matriz
print("Matriz de números complejos:")
print(matriz_compleja)


Matriz de números complejos:
[[1.+2.j 2.-1.j]
 [0.+3.j 4.+0.j]]


In [5]:
# Ejercicio 08


# Crear una matriz de matrices
matriz_de_matrices = np.array([[np.array([1, 2, 3]), np.array([4, 5, 6])],
                               [np.array([7, 8, 9]), np.array([10, 11, 12])]], dtype=object)
print(matriz_de_matrices)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [10 11 12]]]


In [ ]:
#ejercicio 9
# acceder al elemento central
import numpy as np

# Crear una matriz de ejemplo
matriz = np.array([[2, 8, 3],
                   [4, 7, 6],
                   [1, 8, 2]])

# Obtener las dimensiones de la matriz
filas, columnas = matriz.shape

# Calcular las coordenadas del elemento central
fila_central = filas // 2
columna_central = columnas // 2

# Acceder al elemento central
elemento_central = matriz[fila_central, columna_central]

# Mostrar el resultado
print(f"Elemento central de la matriz: {elemento_central}")


Elemento central de la matriz: 7


In [6]:
# Ejercicio 10


def suma_matrices_diferentes_tamanos(matriz1, matriz2):
    # Obtener las dimensiones de ambas matrices
    filas1, columnas1 = matriz1.shape
    filas2, columnas2 = matriz2.shape

    # Crear una nueva matriz del mismo tamaño que la primera matriz
    resultado = np.zeros_like(matriz1)

    # Sumar las partes superpuestas de ambas matrices
    resultado[:filas2, :columnas2] += matriz2

    # Sumar la primera matriz
    resultado += matriz1

    return resultado

# E
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matriz2 = np.array([[7, 8],
                    [9, 10]])

resultado = suma_matrices_diferentes_tamanos(matriz1, matriz2)
print("Resultado de la suma de matrices:")
print(resultado)

Resultado de la suma de matrices:
[[ 8 10  3]
 [13 15  6]]


In [ ]:
#EJERCICIO 11
# Multiplica una matriz por un número.
import numpy as np

# Crear una matriz de ejemplo
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Definir el número por el cual multiplicar la matriz
numero = 3

# Multiplicar la matriz por el número
matriz_resultante = matriz * numero

# Mostrar la matriz resultante
print("Matriz original:")
print(matriz)

print(f"\nMatriz multiplicada por {numero}:")
print(matriz_resultante)


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz multiplicada por 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [7]:
# Ejercicio 12

def media_matriz(matriz):
    return np.mean(matriz)

# Ejemplo de uso
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

media = media_matriz(matriz)
print("Media de los elementos de la matriz:", media)

#### Parte 2

Media de los elementos de la matriz: 5.0


In [ ]:
#ejercicios complejos
#Crea una matriz de números aleatorios de tamaño 100x100
import numpy as np

# Crear una matriz de números aleatorios de tamaño 100x100
matriz_aleatoria = np.random.rand(100, 100)

# Mostrar la matriz resultante
print("Matriz de números aleatorios:")
print(matriz_aleatoria)


Matriz de números aleatorios:
[[0.83581716 0.92816392 0.33865123 ... 0.61468044 0.19788994 0.81909525]
 [0.81226681 0.25489677 0.65370628 ... 0.30109425 0.48908254 0.40722192]
 [0.88231456 0.7825768  0.14129013 ... 0.72542557 0.40457003 0.40583312]
 ...
 [0.26287398 0.66547711 0.9345087  ... 0.03827365 0.73597964 0.41373682]
 [0.0718887  0.68675819 0.49211553 ... 0.58172103 0.88016548 0.95404479]
 [0.36160466 0.03072326 0.25285568 ... 0.65317898 0.47753711 0.98066563]]


In [8]:
# Ejercicio 02

import numpy as np

# Crear una matriz de ejemplo
matriz = np.random.rand(5, 5)

# Calcular la media
media = np.mean(matriz)

# Calcular la mediana
mediana = np.median(matriz)

# Calcular la desviación estándar
desviacion_estandar = np.std(matriz)

# Imprimir los resultados
print("Matriz:")
print(matriz)
print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion_estandar)

Matriz:
[[0.10957781 0.61991977 0.37401747 0.45196188 0.58379844]
 [0.12369414 0.99741567 0.44633693 0.03213449 0.89531984]
 [0.49699594 0.32914419 0.18926841 0.58585224 0.74224779]
 [0.75819316 0.86635678 0.16237807 0.89396961 0.15506311]
 [0.33324758 0.06349912 0.81075915 0.77199553 0.15244669]]
Media: 0.4778237522955773
Mediana: 0.4519618795160797
Desviación estándar: 0.299156089715936


In [ ]:
#ejercicio 3 complejos
#Escribe una función que encuentre el elemento máximo de una matriz
import numpy as np

def encontrar_maximo(matriz):
    # Utilizar la función np.max para encontrar el elemento máximo
    maximo = np.max(matriz)
    return maximo

# Crear una matriz de ejemplo
matriz_ejemplo = np.array([[71, 22, 33],
                           [40, 95, 63],
                           [17, 80, 5]])

# Llamar a la función para encontrar el elemento máximo
maximo_encontrado = encontrar_maximo(matriz_ejemplo)

# Mostrar el resultado
print("Matriz de ejemplo:")
print(matriz_ejemplo)
print(f"\nEl elemento máximo de la matriz es: {maximo_encontrado}")


Matriz de ejemplo:
[[71 22 33]
 [40 95 63]
 [17 80  5]]

El elemento máximo de la matriz es: 95


In [ ]:
#ejercicio 5 complejos
#Escribe una función que encuentre la matriz de covarianza de dos matrices.
import numpy as np

def matriz_covarianza(matriz1, matriz2):
    # Calcular la matriz de covarianza utilizando np.cov
    covarianza = np.cov(matriz1, matriz2, rowvar=False)
    return covarianza

# Crear dos matrices de ejemplo
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matriz2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Llamar a la función para encontrar la matriz de covarianza
matriz_cov = matriz_covarianza(matriz1, matriz2)

# Mostrar el resultado
print("Matriz 1:")
print(matriz1)

print("\nMatriz 2:")
print(matriz2)

print("\nMatriz de covarianza:")
print(matriz_cov)


Matriz 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matriz de covarianza:
[[ 9.  9.  9. -9. -9. -9.]
 [ 9.  9.  9. -9. -9. -9.]
 [ 9.  9.  9. -9. -9. -9.]
 [-9. -9. -9.  9.  9.  9.]
 [-9. -9. -9.  9.  9.  9.]
 [-9. -9. -9.  9.  9.  9.]]
